name: PearDesk Build

on:
  push:
    branches: ["master"]
    tags-ignore: ["*"]
  pull_request:
    branches: ["master"]

jobs:

  build-linux:
    runs-on: ubuntu-22.04
    env:
      GOTOOLCHAIN: local

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.12"
          check-latest: true

      - name: Install deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libx11-dev libxrandr-dev libxcursor-dev libxi-dev \
            libxinerama-dev libgl1-mesa-dev libgles2-mesa-dev libfontconfig1-dev \
            libfreetype6-dev libxtst-dev libxxf86vm-dev pkg-config gcc wget

      - name: Build binary
        run: |
          go build -o peardesk-linux ./cmd/peardesk

      - name: Prepare AppDir
        run: |
          mkdir -p AppDir/usr/bin

          # Copia binario
          cp peardesk-linux AppDir/usr/bin/peardesk

          # Copia AppRun, desktop file e icona dalla cartella assets
          cp assets/AppRun AppDir/AppRun
          chmod +x AppDir/AppRun

          cp assets/peardesk.desktop AppDir/peardesk.desktop
          cp assets/icon.png AppDir/peardesk.png

      - name: Download appimagetool
        run: |
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          export APPIMAGE_EXTRACT_AND_RUN=1

      - name: Build AppImage
        run: |
          export APPIMAGE_EXTRACT_AND_RUN=1
          ./appimagetool-x86_64.AppImage AppDir PearDesk.AppImage

      - uses: actions/upload-artifact@v4
        with:
          name: PearDesk-AppImage
          path: PearDesk.AppImage
